title: "Vera"

markdown: kramdown
liquid:
  error_mode: strict
  strict_filters: true
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .idea
  - README.md

# Theme settings
remote_theme: "pmarsceill/just-the-docs@v0.3.3"
search_enabled: false
color_scheme: dark
aux_links:
  "GitHub org": "https://github.com/VeraDomains"
  "Relaycorp": "https://relaycorp.tech"
heading_anchors: true
gh_edit_link: true
